### ISSUE TITLE
Workshop crate combusts after spawning

### ISSUE THREAD

**Issue by Majkl-J** [Nifnat/Overthrow#3]
The crate appears to spawn inside the wall of the workshop (and slightly in the ground) each time the workshop is placed.

**Comment by Majkl-J** [comment]
Update: Happens only sometimes, seems to be at random.

**Comment by Majkl-J** [comment]
Update: After waiting for multiple months I have decided to take matter into my own hands as I have since gained significant experience in modding Arma.

I will submit a simple fix tomorrow, when I confirm it is, in fact. A reliable fix.

**Comment by Nifnat** [comment]
Solved in #8, thanks for the fix.
